<div class="mdc-layout-grid">
	<div class="mdc-layout-grid__inner">
		<div class="mdc-layout-grid__cell--span-12">
			<div class="mdc-card">
				<h6 class="card-title">Text Field</h6>
				<div class="template-demo">
					<div class="mdc-layout-grid__inner">
						<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
							<div class="mdc-text-field mdc-ripple-upgraded">
								<input class="mdc-text-field__input" id="text-field-hero-input">
								<div class="mdc-line-ripple"></div>
								<label for="text-field-hero-input" class="mdc-floating-label">Name</label>
							</div>
						</div>
						<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
							<div class="mdc-text-field mdc-text-field--outlined">
								<input class="mdc-text-field__input" id="text-field-hero-input">
								<div class="mdc-notched-outline mdc-notched-outline--upgraded">
									<div class="mdc-notched-outline__leading"></div>
									<div class="mdc-notched-outline__notch">
										<label for="text-field-hero-input" class="mdc-floating-label" style="">Name</label>
									</div>
									<div class="mdc-notched-outline__trailing"></div>
								</div>
							</div>
						</div>
						<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
							<div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-leading-icon">
								<i class="material-icons mdc-text-field__icon">favorite</i>
								<input class="mdc-text-field__input" id="text-field-hero-input">
								<div class="mdc-notched-outline mdc-notched-outline--upgraded">
									<div class="mdc-notched-outline__leading"></div>
									<div class="mdc-notched-outline__notch">
										<label for="text-field-hero-input" class="mdc-floating-label" style="">Name</label>
									</div>
									<div class="mdc-notched-outline__trailing"></div>
								</div>
							</div>
						</div>
						<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
							<div class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-trailing-icon">
								<i class="material-icons mdc-text-field__icon">visibility</i>
								<input class="mdc-text-field__input" id="text-field-hero-input">
								<div class="mdc-notched-outline mdc-notched-outline--upgraded">
									<div class="mdc-notched-outline__leading"></div>
									<div class="mdc-notched-outline__notch">
										<label for="text-field-hero-input" class="mdc-floating-label" style="">Name</label>
									</div>
									<div class="mdc-notched-outline__trailing"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>